"""Agent that writes newsletter from summary."""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from src.agents.base_agent import BaseAgent


class WriterAgent(BaseAgent):
    """
    Writes newsletter from summary.

    Final step in pipeline.
    """

    async def _load_context(self, input_path: str) -> Dict[str, Any]:
        """Load summary."""
        print(f"📖 Loading summary from {input_path}")
        content = Path(input_path).read_text()
        return {"summary": content}

    async def _process(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """Write newsletter."""
        summary = context["summary"]

        print(f"✍️  Writing newsletter...")

        prompt = f"""You are writing a daily AI/ML newsletter.

Here's the summary of today's articles:

{summary}

Write an engaging newsletter with:
1. Catchy introduction (2-3 sentences)
2. Main content organized by topic (keep the summaries, add context)
3. Brief conclusion

Use a professional but friendly tone. Include emoji sparingly."""

        newsletter = self._call_llm(prompt)

        return {"newsletter": newsletter, "date": datetime.now().strftime("%Y-%m-%d")}

    async def _save_result(self, result: Dict[str, Any], output_path: str):
        """Save newsletter."""
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "w") as f:
            f.write(f"# AI/ML Daily Newsletter - {result['date']}\n\n")
            f.write(result["newsletter"])
            f.write("\n\n---\n\n")
            f.write(f"*Generated by AI Agent Pipeline*\n")

        print(f"💾 Newsletter saved to {output_path}")
